### PR TITLE
Add build that preserves stringification.

### LINKED ISSUE #3: Support for unsafe-eval?
The call to `new Function()` makes the runtime unusable with a strict CSP.

It's pretty difficult to figure out what `processIncludes` actually does, but for now we take the generated code & export that.

### PR DESCRIPTION
**Pull request by STRML**
For use with fast-async, it is important that both $asyncbind
and $asyncspawn can be stringified and have no dependencies.

To do so, we require the contents of their dependencies and
inline them.

Both unminified and minified source are written. By default,
the minified source is used.

This reduces runtime size slightly (due to the removal of
processIncludes()) and no longer uses eval, making it compatible
with a strict Content-Security-Policy.

Fixes #3

### CODE REVIEW

**Comment by matAtWork** [comment]
I really appreciate the PR (it can be kind of lonely here!), but this method has the downside that any changes to zousan.js and thenable.js have to be implemented in two places, and has a dependency on Uglify which I'd prefer to avoid as a lot of nodent users are just server-side (so Uglify is a lot of code for the small of minification).

I've pushed/published v3.0.3 which should do what you want. On installation it runs the existing runtime (with its simple "processIncludes") and drops the output in ./dist/index.js (since the whole point is that the runtime can be easily rendered), so for browserify/webpack you should simply `require('nodent-runtime/dist')` near the front of your bundle sources.

**Comment by STRML** [comment]
To address your points:
- The Uglify build is not strictly necessary, the only reason I included it was because it appeared you were already doing some rudimentary whitespace & comment trimming.
- The Uglify dep is a devDependency, consumers won't install it.
- Changes to zousan and thenable.js in both places are not necessary - simply run the build at every tag, or like in 1f4704c, run after download on postinstall.
- The current solution has two issues:
  - If extra functions or features are added, the build file will need to be changed as well (because you've written out the function template rather than replaced the function)
  - If you're going to commit to a build, then there's no reason to use `./runtime.js` as the entry point, it just introduces startup overhead; just use `dist/index.js` as the `"main"`.

**Comment by matAtWork** [comment]
You're right in many respects. 

Avoiding Uglify is a personal thing - I just like to keep dependencies to a minimum.

Unless I misunderstood something, any changes to zousan and thenable.js would need to be done twice as legacy code can refer to either the 'runtime' (quite new) or the files directly, and placing a `require` in the runtime stops it being serializable with no dependencies. I don't encourage people to refer to specific implementation files, but before the runtime existed as a separate module, that's what people did.

I really hope NOT to add anything new to the runtime (the two functions have basically existed forever, and external interface hasn't changed in maybe 2 years). In fact, the later builds have a "no runtime" which puts the burden into your Promise implementation.

The final point (not using `/dist`) was simply to avoid making unnecessary changes - I just ran into that in https://github.com/MatAtBread/fast-async/issues/24 where a small change (not generating the runtime if the file contained no asyncs/awaits) broke someone's build. I'm just happier extending the interface to meet your needs than changing an existing one.

One issue here is that fast-async (nodent via babel) doesn't get the same level of testing as nodent by itself does - I just don't use babel enough, so I'm always more nervous about making changes.

**Comment by STRML** [comment]
> Unless I misunderstood something, any changes to zousan and thenable.js would need to be done twice as legacy code can refer to either the 'runtime' (quite new) or the files directly, and placing a require in the runtime stops it being serializable with no dependencies. I don't encourage people to refer to specific implementation files, but before the runtime existed as a separate module, that's what people did.

Well, the runtime today already has a `require()`, but the point is that changing the `"main"` to `dist/index.js` means that every consumer is getting one with serializable functions. The difference is, we're doing it at publish time, rather than making consumers do it themselves at install time with eval hacks. So technically the `./runtime.js` probably belongs in a `src/` folder and nobody should be requiring it directly.

So updating `zousan.js` for whatever reason would be a matter of:
- Update the file
- Run the build.

Same as in 1f4704c.

I understand re: breaking someone's build, but honestly that's the whole point of `"main"` - to a certain degree, if you're doing something weird like `require('nodent-runtime/runtime')` rather than the package itself, you are relying on internals which should not be encouraged or supported.

**Pull request closed without merging**
